version: "3.8"

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: "1000M"
        reservations:
          cpus: "0.2"
          memory: "256M"

    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ngproxy.rule=Host(`proxy.vidnest.fun`)"
      - "traefik.http.routers.ngproxy.entrypoints=web"
      - "traefik.http.services.ngproxy.loadbalancer.server.port=3000"
      - "traefik.http.routers.ngproxy.middlewares=redirect-to-https"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      # HTTPS router for proxy.vidnest.fun
      - "traefik.http.routers.ngproxy-secure.rule=Host(`proxy.vidnest.fun`)"
      - "traefik.http.routers.ngproxy-secure.entrypoints=websecure"
      - "traefik.http.routers.ngproxy-secure.tls=true"
      - "traefik.http.routers.ngproxy-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.ngproxy-secure.middlewares=strip-api"
      # HTTP -> HTTPS redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=gamingsss628@gmail.com"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  autoheal:
    image: willfarrell/autoheal:latest
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always